privacyPolicyUrl=
rakuten.accessKey.dev=
rakuten.accessKey.prod=
rakuten.affiliateId.dev=
rakuten.affiliateId.prod=
rakuten.applicationId.dev=
rakuten.applicationId.prod=
rakuten.referer.dev=
rakuten.referer.prod=
rakuten.developersUrl=
termsOfUseUrl=
